name: Deploy Cloudflare Pages

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      CLOUDFLARE_API_TOKEN: xxxxxxxxxxxxxxxxxxx
      CLOUDFLARE_ACCOUNT_ID: xxxxxxxxxxxxxxxxxx
      CUSTOM_DOMAIN_SUFFIX: bibica.net
      SERVER_PREFIX: iserver
      SERVER_COUNT: 19

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install -g wrangler

      - name: Generate page configurations
        run: node scripts/generate-pages.js

      - name: Deploy pages
        run: |
          echo "Cấu hình DNS CNAME records:"
          echo ""
          
          for i in $(seq 1 $SERVER_COUNT); do
            PROJECT_NAME="${SERVER_PREFIX}${i}"
            CUSTOM_DOMAIN="${PROJECT_NAME}.${CUSTOM_DOMAIN_SUFFIX}"
          
            echo ""
            echo "Deploying project: $PROJECT_NAME..."
          
            cd "${SERVER_PREFIX}/${PROJECT_NAME}"
          
            sleep 1
          
            # Kiểm tra xem project đã tồn tại chưa
            if ! wrangler pages project list | grep -q "$PROJECT_NAME"; then
              echo "Creating new project $PROJECT_NAME..."
              wrangler pages project create "$PROJECT_NAME" --production-branch=main
            fi
          
            sleep 1
          
            # Deploy project, lấy URL trả về
            DEPLOYMENT_URL=$(wrangler pages deploy . --project-name="$PROJECT_NAME" --commit-dirty=true | grep -o 'https://[^[:space:]]*\.pages\.dev')
            PAGES_DOMAIN="${DEPLOYMENT_URL#https://}"  # loại bỏ tiền tố https:// để dùng cho CNAME
          
            # Kiểm tra domain đã được add chưa
            DOMAIN_EXISTS=$(curl -s -X GET "https://api.cloudflare.com/client/v4/accounts/${CLOUDFLARE_ACCOUNT_ID}/pages/projects/${PROJECT_NAME}/domains" \
              -H "Authorization: Bearer ${CLOUDFLARE_API_TOKEN}" | grep -o "$CUSTOM_DOMAIN" | head -1)
          
            sleep 1
          
            # Thêm domain nếu chưa có
            if [ -z "$DOMAIN_EXISTS" ]; then
              echo "Adding custom domain: $CUSTOM_DOMAIN..."
              curl -s -X POST "https://api.cloudflare.com/client/v4/accounts/${CLOUDFLARE_ACCOUNT_ID}/pages/projects/${PROJECT_NAME}/domains" \
                -H "Authorization: Bearer ${CLOUDFLARE_API_TOKEN}" \
                -H "Content-Type: application/json" \
                --data '{"name":"'"$CUSTOM_DOMAIN"'"}' > /dev/null
            else
              echo "Custom domain $CUSTOM_DOMAIN already exists, skipping..."
            fi
          
            echo "🔗 CNAME $CUSTOM_DOMAIN -> $PAGES_DOMAIN"
          
            cd ../..
            sleep 1
          done
          
          echo ""
          echo "Hoàn thành deploy tất cả projects!"
